# Generated by Django 5.1.3 on 2024-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkout_method',
            field=models.CharField(blank=True, choices=[('meet_farmer', 'Meet Farmer'), ('online_payment', 'Online Payment')], max_length=50, null=True),
        ),
    ]
