# Generated by Django 5.1.3 on 2024-12-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_checkout_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='crop_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='farmer_contact',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='farmer_location',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity_requested',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
            ],
        ),
    ]
